### ISSUE TITLE
Error while running example WordCountTopology

### ISSUE THREAD

**Issue by harsha273** [hmsonline/storm-cassandra-cql#58]
Guys,

I am quite new to trident and cassandra. While trying to run the  wordcount example , am getting this exception midway through the run. Any ideas please?

```
DEBUG (com.hmsonline.trident.cql.CassandraCqlMapState:165) - Putting the following keys: [[went, spout1], [and, spout2]] with values: [73, 73]
ERROR (clojure.tools.logging$eval37$fn__43:16) - Async loop died!
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 1
	at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:107)
	at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:78)
	at backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:77)
	at backtype.storm.daemon.executor$eval5170$fn__5171$fn__5183$fn__5230.invoke(executor.clj:745)
	at backtype.storm.util$async_loop$fn__390.invoke(util.clj:433)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.hmsonline.trident.cql.CassandraCqlMapState.checkCassandraException(CassandraCqlMapState.java:227)
	at com.hmsonline.trident.cql.CassandraCqlMapState.multiGet(CassandraCqlMapState.java:157)
	at storm.trident.state.map.CachedMap.multiGet(CachedMap.java:52)
	at storm.trident.state.map.NonTransactionalMap.multiGet(NonTransactionalMap.java:39)
	at storm.trident.state.map.SnapshottableMap.multiGet(SnapshottableMap.java:37)
	at storm.trident.operation.builtin.MapGet.batchRetrieve(MapGet.java:31)
	at storm.trident.operation.builtin.MapGet.batchRetrieve(MapGet.java:28)
	at storm.trident.planner.processor.StateQueryProcessor.finishBatch(StateQueryProcessor.java:84)
	at storm.trident.planner.SubtopologyBolt.finishBatch(SubtopologyBolt.java:152)
	at storm.trident.topology.TridentBoltExecutor.finishBatch(TridentBoltExecutor.java:252)
	at storm.trident.topology.TridentBoltExecutor.checkFinish(TridentBoltExecutor.java:285)
	at storm.trident.topology.TridentBoltExecutor.execute(TridentBoltExecutor.java:364)
	at backtype.storm.daemon.executor$eval5170$fn__5171$tuple_action_fn__5173.invoke(executor.clj:630)
	at backtype.storm.daemon.executor$mk_task_receiver$fn__5091.invoke(executor.clj:398)
	at backtype.storm.disruptor$clojure_handler$reify__1894.onEvent(disruptor.clj:58)
	at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:104)
	... 6 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at storm.trident.tuple.TridentTupleView.getValue(TridentTupleView.java:227)
	at storm.trident.tuple.TridentTupleView.get(TridentTupleView.java:222)
	at com.hmsonline.trident.cql.example.wordcount.WordCountAndSourceMapper.retrieve(WordCountAndSourceMapper.java:41)
	at com.hmsonline.trident.cql.example.wordcount.WordCountAndSourceMapper.retrieve(WordCountAndSourceMapper.java:15)
	at com.hmsonline.trident.cql.CassandraCqlMapState.multiGet(CassandraCqlMapState.java:137)
	... 20 more

```

**Comment by gaurchandan** [comment]
Actually problem is in WordCountAndRowMapper.java
 @Override
    public Statement retrieve(List<String> keys) {
        // Retrieve all the columns associated with the keys
        Select statement = QueryBuilder.select().column(SOURCE_KEY_NAME)
                .column(WORD_KEY_NAME).column(VALUE_NAME)
                .from(KEYSPACE_NAME, TABLE_NAME);
        statement.where(QueryBuilder.eq(SOURCE_KEY_NAME, keys.get(0)));
//Please comment the below line because in keys we r not sending composite primary key
// we are just sending a single word as key (check DRPCClient request as we not giving any
// spout source there
//        statement.where(QueryBuilder.eq(WORD_KEY_NAME, keys.get(1)));
        return statement;
    }


so this will definately resolves the issue.
All the best
